apiVersion: v2
appVersion: 3.2.0
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: Spark for PLAS platform
home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/spark
keywords:
- plas
- spark
name: spark
sources:
- https://github.com/PlatformedTasks/Documentation
- https://github.com/bitnami/bitnami-docker-spark
- https://spark.apache.org/
version: 6.0.0