apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-cm
  labels:
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}
    app: platform-spark
data:
  executor.config: |
    ## executor.config
  executor.init: |
    ## executor.init